services:
  - type: worker
    name: live-phone-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_worker.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
